### PR TITLE
Improve image caching

### PR DESCRIPTION
**Pull request by davidoskky**
## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

This closes issue #324

Right now I am caching images from unread and starred articles only. Moreover with this change it will store up to 200 articles of each category: unread, read and starred.

### CODE REVIEW

**Comment by davidoskky** [comment]
Glide does not natively support the svg format. I made sure to have it access only image formats it does support.
This fixes the crash with the feed https://www.journalduhacker.net/rss
I will look for a way to support svg images in the future, for now it may be better to merge this fix in order to have a stable version

**Review by aminecmi — CHANGES_REQUESTED** [review]
Thanks for the quick fix.

This fixes the crashes. Can you see take a look at my comments ?

**Comment by davidoskky** [comment]
I removed all the code regarding the background sync, in this way this PR focuses only on fixing those crashes.
I'll make another PR for the background sync.

**Review by aminecmi — APPROVED** [review]

**Comment by aminecmi** [comment]
Closes #324

**Pull request merged**
