### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by davidoskky**
## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

I now realized it's over one year I've been working on this app :)

### CODE REVIEW

**Comment by aminecmi** [comment]
> I now realized it's over one year I've been working on this app :)
 
 Thanks a lot for your help !

**Comment by aminecmi** [comment]
Did you try to test the app with the minSdk to see if this does not break anything ?

**Comment by davidoskky** [comment]
I tested it on sdk version 24 and 30, not on the minimum supported.
I'm unable to fully test the app on api versions previous to 24 due to  #339.

**Comment by aminecmi** [comment]
#339 was fixed by updating the minSdk to version 21. I'll try to find what changed and made testing on this version impossible.

**Comment by aminecmi** [comment]
Just tested with version 21. Seems to work.

**Pull request merged**
