### PR TITLE
Expand images on tap

### PR DESCRIPTION
**Pull request by davidoskky**
## Types of changes

- [x] I have read the **CONTRIBUTING** document.
- [x] My code follows the code style of this project.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [x] This is **NOT** translation related. (See [here](https://github.com/aminecmi/ReaderforSelfoss/pull/170#issuecomment-355715654))

This closes issue #178

I started implementing a function to detect taps on images in webview, it still doesn't do anything though.

To expand the image I looked at the Pocket application who does it opening the image in full screen and including three buttons:  one to close the image and the other two to go to the next/previous image.
If you like this behavior I might start preparing a fragment to show the image in fullscreen.

### CODE REVIEW

**Comment by aminecmi** [comment]
That would be really great, yes !

**Comment by davidoskky** [comment]
While not complete, this is now functional. However there is a brief white flash while loading the image which is not very nice.
It might be better to use an imageview to avoid the flash and to support this functionality offline as well.

**Comment by aminecmi** [comment]
Thanks a lot. I’ll try to test it to see how that works.

And yes, supporting the functionality when offline would be awesome !

**Comment by aminecmi** [comment]
Just tested it, and it works great.

For some reasons, one specific picture wouldn't open, and opened in chrome, [https://imgur.com/a/eBzyXXz](Here is the preview).

I'm not sure it should open any browser if it couldn't load the picture, but display an error message instead.

I was also wondering why you didn't use an `androidx.appcompat.widget.Toolbar` for the back button ? It seems kind of weird to have a floating button on top.

And FWI, I had to update the `constraintlayout` library to be able to build the app. Did you have to do it too ?

**Comment by davidoskky** [comment]
Using a Toolbar might be a better solution in fact, I'll look into it.
I did not have to update any library before building the app, though I just installed all the libraries and so I might just have the library updated already.
I am sorry if some of my programming is strange, but I never wrote a single line of code for android before the PR's I made here...
I am actually an UX designer, working on this project is giving me a little bit of insight of what programmers have to do after I hand them the design.

**Comment by aminecmi** [comment]
No problem at all.

Again, thanks for helping with the app !

**Comment by davidoskky** [comment]
It is now possible to swipe to go through all the images in the article. I had to use a new library to do this, check if it is fine.
The problem you had with that image opening in the browser should now be solved.
I reverted to the Toolbar for navigation, but I wasn't able to make it transparent in order to have more screen space to display the image.

Regarding having this function offline, as far as I can tell images are not being stored in the database right now. I guess a method to store images in the database should be implemented first.
Strangely however some images do get cached and get displayed even while offline right now.

**Comment by aminecmi** [comment]
> It is now possible to swipe to go through all the images in the article. I had to use a new library to do this, check if it is fine.

Great ! 

> The problem you had with that image opening in the browser should now be solved.

Thanks !

I reverted to the Toolbar for navigation, but I wasn't able to make it transparent in order to have more screen space to display the image.

No problem.

> Regarding having this function offline, as far as I can tell images are not being stored in the database right now. I guess a method to store images in the database should be implemented first. Strangely however some images do get cached and get displayed even while offline right now.

I just added two comments that may help caching the images if you use `Glide`. I’m not sure if it’s possible, but maybe Glide will let you cache the pictures even in the background job that sync the content periodically.

**Comment by davidoskky** [comment]
All the images now get cached during the background sync. This allows reading articles with images while offline and, of course, using this functionality offline.
I tested it on my phone and it works fine, but I have no idea how to go about creating unit tests, it may be better if you tested it as well, as there may very well be some problems.

**Comment by aminecmi** [comment]
@davidoskky I'm trying to launch the app, and have this error:
`java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.`
Didn't you have to change this ?

**Review by aminecmi — CHANGES_REQUESTED** [review]

**Comment by davidoskky** [comment]
I did get that error as well, however I did not change the version number myself as I wasn't sure that was alright.

What I did was uninstall the application and then reinstall it, this solved the problem and let me use it. Indeed changing the version number might be required before publishing it.

Regarding the webview: I actually intended to switch to an imageview after the implementation of Glide, but I completely forgot about that. I will switch them soon.

**Comment by davidoskky** [comment]
I switched from WebView to ImagevView. Since ImageView does not have a function to zoom with gestures I used a library who implements zooming.
Moreover I created an activity with a pager to have a smoother transition between images when swiping.

**Comment by aminecmi** [comment]
> I did get that error as well, however I did not change the version number myself as I wasn't sure that was alright.

I'll take a look at this then, and get back to you when I finished testing.

**Comment by aminecmi** [comment]
Hey @davidoskky I just fixed the issue with the migration.

It was due to the model changes for icons and thumbnails being now optional with some of your other fixes.

This is now available on master.

The imageviewer work really well too ! Thanks for this !

If you could just resolve the conflict with the `app/build.gradle`, I'll be happy to merge the PR !

**Review by aminecmi — DISMISSED** [review]

**Comment by davidoskky** [comment]
The conflict is solved.

**Review by aminecmi — APPROVED** [review]

**Pull request merged**
